### ISSUE TITLE
Mainactivity  re-opened cannot be traced

### ISSUE THREAD

**Issue by cike978** [facemoji/mocap4face#5] opened 2021-12-16 09:29 UTC
Only the first open MainActivity can be tracked.  when back to SplashActivity and reopen Mainactivity the track result is null. 

The test code is as follows（modify SplashAtivity）：

    override fun onResume() {
        super.onResume()
        Timer("Splash", false).schedule(5000) {
            startMainActivity()
        }
    }

**Comment by cike978** [comment] 2021-12-16 09:38
The Repetition steps is when the app is not killed, go back to the SplashActivity and enter MainActicity again

**Comment by will4621d** [comment] 2022-01-06 07:55
Same problem, the error is "OpenGLResizer20: setup OES texture: glError 1282: invalid operation"

**Comment by will4621d** [comment] 2022-03-25 02:43
@karelp Hi, is there any update about this issue?

**Comment by karelp** [comment] 2022-03-25 09:16
Hi, I’m able to reproduce it but it takes quite a bit of internal refactor to get fixed, the problem is that sometimes when closing/reopening activities the OpenGL context gets lost without the camera tracker getting information about it. Will probably need to rethink the way we handle OpenGL to work around this problem.

**Comment by lonelyssl** [comment] 2022-05-16 01:59
I also encountered this mistake and urgently need to solve it. Is there any way to solve this problem now?  thank you

**Comment by karelp** [comment] 2022-05-16 09:28
Hey, yes, the workaround for now is to create new CameraWrapper when the activity gets restarted.

**Comment by pengzhenkun** [comment] 2022-08-06 10:26
Is there any solution to this problem? It is in urgent need of repair. Thank you

**Comment by pengzhenkun** [comment] 2022-08-06 10:36
> 我也遇到了这个错误，迫切需要解决它。现在有办法解决这个问题吗？谢谢您



> I also encountered this mistake and urgently need to solve it. Is there any way to solve this problem now? thank you

Is there a solution?

**Comment by pengzhenkun** [comment] 2022-08-06 10:36
> I also encountered this mistake and urgently need to solve it. Is there any way to solve this problem now? thank you

Is there a solution?

**Comment by karelp** [comment] 2022-08-29 13:01
Fixed in 0.4.0.

**Closed as completed by karelp** 2022-08-29 13:01 UTC
Labels: bug
